#!/bin/sh
bspc config border_width         2
bspc config window_gap          15

bspc monitor DP-1    -d 1 2 3 4 5 6 7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
pointer_follows_monitor true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config top_padding 30

bspc config focused_border_color '#b3b1b1'
bspc confic normal_border_color '#252b31'
bspc config presel_feedback_color '#BE7C6B'

bspc rule -a URxvt:Quake state=floating
bspc rule -a URxvt:Doom state=floating
bspc rule -a Thunar state=floating
bspc rule -a feh state=floating
bspc rule -a dota2 locked=on state=fullscreen
bspc rule -a Steam desktop=^4 follow=off
bspc rule -a tk state=floating

compton --unredir-if-possible &
nitrogen --restore &
polybar center &

