#!/bin/sh
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc monitor -d 1 2 3 4 5 6 7
bspc monitor HDMI-2 -d 8 9

bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config top_padding 30

bspc config focused_border_color '#b3b1b1'
bspc confic normal_border_color '#252b31'
bspc config presel_feedback_color '#BE7C6B'

bspc rule -a URxvt:Quake sticky=on state=floating border=off
bspc rule -a URxvt:Doom state=floating border=off sticky=on
bspc rule -a URxvt:Wolfenstein state=floating border=off sticky=on
bspc rule -a Thunar state=floating
bspc rule -a feh state=floating
bspc rule -a tk state=floating
bspc rule -a Emacs state=tiled

sxhkd &
compton --unredir-if-possible &
dunst &
kdeconnect-cli &
nitrogen --restore &
wmname LG3D &
polybar top &
thunar --daemon &
redshift &

