#!/usr/bin/bash
theme=`ls -a $HOME | grep ".Xresources-" | cut -c13-17`

if [[ $theme == *"light"* ]]; then
    echo "dark"
    `mv $HOME/.Xresources $HOME/.Xresources-dark`
    `mv $HOME/.Xresources-light $HOME/.Xresources`
    `sed 's/Dark+ Material/Default Light+/g' $HOME/.config/Code/User/settings.json > $HOME/.config/Code/User/settings2.json`
    `mv $HOME/.config/Code/User/settings2.json $HOME/.config/Code/User/settings.json`
    `sed 's/:colorscheme hybrid/:colorscheme lucius/g' $HOME/.config/nvim/init.vim > $HOME/.config/nvim/init2.vim`
    `mv $HOME/.config/nvim/init2.vim $HOME/.config/nvim/init.vim`
else
    echo "light"
    `mv $HOME/.Xresources $HOME/.Xresources-light`
    `mv $HOME/.Xresources-dark $HOME/.Xresources`
    `sed 's/Default Light+/Dark+ Material/g' $HOME/.config/Code/User/settings.json > $HOME/.config/Code/User/settings2.json`
    `mv $HOME/.config/Code/User/settings2.json $HOME/.config/Code/User/settings.json`
    `sed 's/:colorscheme lucius/:colorscheme hybrid/g' $HOME/.config/nvim/init.vim > $HOME/.config/nvim/init2.vim`
    `mv $HOME/.config/nvim/init2.vim $HOME/.config/nvim/init.vim`
fi

`xrdb $HOME/.Xresources`
`pkill -HUP urxvt`
`mv $HOME/.config/nitrogen/bak/bg-saved-other.cfg $HOME/.config/nitrogen/`
`mv $HOME/.config/nitrogen/bg-saved.cfg $HOME/.config/nitrogen/bak/bg-saved-other.cfg`
`mv $HOME/.config/nitrogen/bg-saved-other.cfg $HOME/.config/nitrogen/bg-saved.cfg`
eval "nitrogen --restore &"

`pkill polybar`
eval "polybar top-left &"
eval "polybar top-right &"
